# This file will control how this project is configured on your
# target Strata servers.

# Display name of the Project. Must be Unique per Strata instance.
name: tpcds
description: True model representing tpcds data warehouse

# The production branch. This will be the branch used by 
# default. Only developers can actually change branches for
# testing in th app.
production_branch: master
