# This file will control how this project is configured on your
# target Strata servers.

# Display name of the Project. Must be Unique per Strata instance.
name: TPCDS - Tutorial 
description: A nearly complete model of the TPC DS benchmark system. 

# The production branch. This will be the branch used by 
# default. Only developers can actually change branches for
# testing in th app.
production_branch: master
